<?php

namespace App\Http\Middleware;

use App\Models\User;
use Closure;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
    }

    public function handle($request, Closure $next, ...$guards)
    {
        if (!$request->routeIs('login') && !in_array($request->user()->role, [
            User::ROLE_DRIVER, User::ROLE_ADMIN
        ])) {
            abort(403);
        }

        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    }
}
